#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Geo-IP
Version  : 1.51
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/MA/MAXMIND/Geo-IP-1.51.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MA/MAXMIND/Geo-IP-1.51.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libg/libgeo-ip-perl/libgeo-ip-perl_1.51-1.debian.tar.xz
Summary  : 'Look up location and network information by IP Address'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Geo-IP-man

%description
# NAME
Geo::IP - Look up location and network information by IP Address
# VERSION

%package man
Summary: man components for the perl-Geo-IP package.
Group: Default

%description man
man components for the perl-Geo-IP package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Geo-IP-1.51
mkdir -p %{_topdir}/BUILD/Geo-IP-1.51/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Geo-IP-1.51/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Geo/IP.pm
/usr/lib/perl5/site_perl/5.26.1/Geo/IP/Record.pm
/usr/lib/perl5/site_perl/5.26.1/Geo/IP/Record.pod

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Geo::IP.3
/usr/share/man/man3/Geo::IP::Record.3
